export const TYPES = {
  AuthRepository: Symbol.for("AuthRepository"),
  PendingSignupRepository: Symbol.for("PendingSignupRepository"),
  PasswordHasher: Symbol.for("PasswordHasher"),
  SecretCipher: Symbol.for("SecretCipher"),
  PhoneFormatter: Symbol.for("PhoneFormatter"),
  AuthErrorMapper: Symbol.for("AuthErrorMapper"),
  AuthPolicy: Symbol.for("AuthPolicy"),
  SignupUseCase: Symbol.for("SignupUseCase"),
  LoginUseCase: Symbol.for("LoginUseCase"),
  ForgotPasswordUseCase: Symbol.for("ForgotPasswordUseCase"),
  ResetPasswordUseCase: Symbol.for("ResetPasswordUseCase"),
  GetProfileUseCase: Symbol.for("GetProfileUseCase"),
  ResendEmailVerificationUseCase: Symbol.for("ResendEmailVerificationUseCase"),
  SendEmailOtpUseCase: Symbol.for("SendEmailOtpUseCase"),
  VerifyEmailOtpUseCase: Symbol.for("VerifyEmailOtpUseCase"),
  SendPhoneOtpUseCase: Symbol.for("SendPhoneOtpUseCase"),
  VerifyPhoneOtpUseCase: Symbol.for("VerifyPhoneOtpUseCase"),
  RefreshTokenUseCase: Symbol.for("RefreshTokenUseCase"),
  LogoutUseCase: Symbol.for("LogoutUseCase"),
  AuthController: Symbol.for("AuthController"),
  NotificationRepository: Symbol.for("NotificationRepository"),
  NotificationProvider: Symbol.for("NotificationProvider"),
  RegisterPushTokenUseCase: Symbol.for("RegisterPushTokenUseCase"),
  NotificationController: Symbol.for("NotificationController"),
};
